### ISSUE TITLE
hybrid-avisynth-extension

### ISSUE THREAD

**Issue by muzena** [darealshinji/hybrid-debian#2]
@darealshinji 
In Linux Mint 19 hybrid-avisynth-extension package from this [PPA](https://launchpad.net/~djcj/+archive/ubuntu/hybrid) don't work.
In install.sh script download link dosen't work, I think.

wget -q -t 1 --timeout=4 --spider http://www.selur.de/sites/default/files/hybrid_downloads/avisynth/avisynthExtension_.7z

**Comment by darealshinji** [comment]
I've removed all the packages from the PPA, because I'm no longer interested in maintaining it. Sorry for the inconvenience.
